DROP DATABASE IF EXISTS fec;

CREATE DATABASE fec;

USE fec;

CREATE TABLE product_description (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(500) NOT NULL,
    title VARCHAR(100) NOT NULL
);

/*  Execute this file from the command line by typing:
 *    mysql -u root < db/schema.sql
 *  to create the database and the tables.*/

INSERT into product_description (description) VALUES ("Limitless classic innovation mens available access skate homage inspired. Essentials exclusive access premium, sport force pack special exclusive trancendant available retro tech skate. Stealth limitless brand advance tech, zoom inspired athlete air vapormax brand collection.");
INSERT into product_description (description) VALUES ("Max culture collection ethos brand, skate premium force cortez access. Upper offwhite collection launch launch training inspired offwhite force, fly trancendant attack reserved. Retro training womens breaking unlock kickoff strike sport offwhite.");        
INSERT into product_description (description) VALUES ("Innovate reserved fly, importance finesse strike force swoosh futuristic hurache zoom available virgil. Strike upper stealth ignite vapormax, ignite flyknit access zoom future training. Trancendant retailers launch court kickoff world, global sneakers transformation versatile snkrs offwhite transformation reserved.");
INSERT into product_description (description) VALUES ("Collection knit explore flyknit legendary importance exclusive. Fly breaking tech, access significant exclusive futuristic finesse stealth finesse. Advance run max run exclusive finesse ignite inspired.");
INSERT into product_description (description) VALUES ("Fly explore pattern innovation sport global, offwhite kickoff court culture launch vapormax. Premium 
fly clothing stealth attack, attack skate culture launch breaking importance icon. Clothing retro sport ultra limitless available, jordan legendary exclusive tech vapormax shilouette.");
INSERT into product_description (description) VALUES ("Court reserved access pattern jordan snkrs unlock. Air sport upper max, world innovation flyknit hurache reserved knit. Vapormax knit ultra swoosh, explore cortez jordan significant cortez available futuristic.");
INSERT into product_description (description) VALUES ("Limitless cortez flight, global pack air strike kickoff quick court kickoff clothing. Global ignite training access equality snkrs lab. Shilouette sneakers retro knit access attack, vapormax inspired court flight collection finesse zoom.");
INSERT into product_description (description) VALUES ("Gear jordan court air explore importance max access fly offwhite, flight tech jordan court. Kickoff retro unlock force kickoff future future virgil. World versatile gear stength versatile snkrs innovate innovation.");
INSERT into product_description (description) VALUES ("Shilouette stealth ultra snkrs strike, legendary fly ignite culture homage transformation offwhite. Inspired virgil retailers skate jordan icon classic vapormax. Snkrs air innovate, explore essentials equality legendary equality gear quick world exclusive.");
INSERT into product_description (description) VALUES ("Swoosh homage running strike pattern access legendary. Special style explore retro exclusive knit unlock. Brand ignite premium pattern advance, global reserved max snkrs retailers.");
INSERT into product_description (description) VALUES ("Essentials breaking member hurache transformation, importance cortez access cortez world zoom access 
explore breaking. Access future knit reserved icon ultra virgil quick, collection collection icon special sport. Transformation versatile futuristic womens 
snkrs trancendant global essentials, finesse global mens sport sport.");
INSERT into product_description (description) VALUES ("Classic importance essentials special brand sneakers gear running style, exclusive culture tech importance. Limitless clothing member kickoff, stength flyknit attack innovation exclusive womens kickoff vapormax. Gear pattern special breaking offwhite world 
culture, jordan gear importance reserved kickoff knit unlock.");
INSERT into product_description (description) VALUES ("Transformation sport strike quick, ultra vapormax max exclusive classic cortez. Flight max ethos run 
exclusive, kickoff vapormax air launch pattern upper. Air swoosh quick finesse exclusive culture, breaking special breaking transformation gear.");
INSERT into product_description (description) VALUES ("Mens inspired upper access ultra premium ethos max. Premium fly classic kickoff custom reserved premium flight future. Cortez skate attack significant classic innovate jordan.");
INSERT into product_description (description) VALUES ("Offwhite mens air classic run unlock cortez. Stealth culture brand reserved training sneakers inspired collection. Shilouette innovate significant knit ignite unlock style air.");
INSERT into product_description (description) VALUES ("Knit limitless court pack stealth futuristic finesse strike reserved. Available max brand trancendant unlock legendary court access significant essentials, clothing sport inspired ignite. Access essentials air mens, futuristic stealth trancendant attack advance special equality futuristic.");
INSERT into product_description (description) VALUES ("Global athlete future access significant custom athlete global. Member icon stealth, flyknit special 
importance skate zoom snkrs breaking access classic athlete. Lab virgil breaking kickoff pattern reserved run sport.");
INSERT into product_description (description) VALUES ("Swoosh skate importance upper future clothing mens. Premium lab flyknit skate jordan transformation access innovation. Versatile pack transformation advance retro futuristic transformation offwhite gear.");
INSERT into product_description (description) VALUES ("Homage access shilouette, limitless vapormax stength retailers gear gear world. Innovate fly swoosh special available trancendant homage. Innovate significant breaking air retailers, collection lab global retailers mens knit.");
INSERT into product_description (description) VALUES ("Essentials custom strike available style exclusive available ultra. Access attack virgil clothing icon retro finesse exclusive. Pack sport collection trancendant homage, unlock skate zoom finesse shilouette force.");
INSERT into product_description (description) VALUES ("Retro court hurache, upper versatile gear breaking cortez flyknit innovate ultra stealth gear available. Special kickoff pattern zoom global zoom, quick icon member cortez knit culture world advance. Transformation flyknit attack snkrs jordan, innovate access access strike finesse finesse pack.");
INSERT into product_description (description) VALUES ("Court offwhite swoosh exclusive trancendant, upper strike gear innovation tech swoosh. Premium heritage lab retro force womens ultra flyknit unlock. Max gear classic attack, launch knit reserved strike lab exclusive sport retro.");
INSERT into product_description (description) VALUES ("Advance jordan futuristic launch fly, upper launch essentials style equality running. Launch skate innovate reserved breaking vapormax lab innovate trancendant. Clothing importance finesse sneakers future stealth ultra reserved.");
INSERT into product_description (description) VALUES ("Flight premium flyknit lab, vapormax lab fly fly premium available. Offwhite heritage access collection pack ignite, gear virgil hurache offwhite max innovate jordan mens. Training pattern attack global icon tech, advance sneakers force breaking.");        
INSERT into product_description (description) VALUES ("Classic culture special, gear quick significant access reserved max special tech force. Flight pattern reserved ignite innovation collection kickoff, icon access collection jordan. Future air snkrs strike style, global womens air sneakers legendary ethos.");
INSERT into product_description (description) VALUES ("Kickoff jordan strike access innovate, air ethos stength snkrs lab stealth shilouette knit transformation. Pattern kickoff unlock access virgil advance importance custom future, advance air gear access exclusive. Limitless trancendant premium womens vapormax breaking exclusive retro finesse.");
INSERT into product_description (description) VALUES ("Stealth explore world, force attack kickoff inspired shilouette access shilouette fly hurache stength breaking. Custom kickoff strike transformation inspired clothing transformation. Collection exclusive limitless ethos retailers innovation attack.");      
INSERT into product_description (description) VALUES ("Essentials athlete inspired retro versatile jordan world. Stength transformation versatile pattern retailers future stealth clothing advance. Advance knit innovation flight vapormax lab classic classic court.");
INSERT into product_description (description) VALUES ("Access flyknit legendary kickoff world member kickoff, strike futuristic tech lab shilouette jordan custom. Advance collection reserved womens upper future, air swoosh max athlete available kickoff sport significant. Access court brand access stength sneakers skate.");
INSERT into product_description (description) VALUES ("Unlock collection exclusive hurache stealth stealth, ethos zoom ethos versatile custom jordan. Futuristic training retro running finesse explore tech mens pack. Special snkrs shilouette classic womens offwhite force innovate.");
INSERT into product_description (description) VALUES ("Pack unlock fly breaking gear strike retro, strike trancendant upper snkrs future attack access. Futuristic global icon force running retro, attack stength collection force swoosh collection athlete stength. Swoosh skate training access global available skate, special homage training global available premium retailers.");
INSERT into product_description (description) VALUES ("Fly transformation equality futuristic trancendant clothing, innovation member sport heritage. Shilouette explore stength culture, exclusive kickoff retailers air skate innovate. Exclusive versatile innovate homage knit ignite training.");
INSERT into product_description (description) VALUES ("Access pattern brand kickoff ultra limitless ultra. Pattern stength retro legendary air sneakers jordan run limitless. Heritage importance flight max gear, ethos access limitless air innovate virgil breaking.");
INSERT into product_description (description) VALUES ("Advance shilouette cortez member icon member importance. Limitless strike air cortez shilouette, stealth brand gear classic knit jordan kickoff culture. Transformation homage reserved cortez reserved legendary stealth flight.");
INSERT into product_description (description) VALUES ("Essentials running flight, snkrs sport ignite mens access snkrs legendary. Exclusive access explore breaking quick legendary virgil. Cortez quick gear stength, sport equality sneakers future vapormax collection max.");
INSERT into product_description (description) VALUES ("Lab shilouette offwhite hurache clothing, run running sport culture trancendant attack. Air heritage 
collection offwhite clothing run launch sneakers, flyknit knit world collection womens vapormax. Legendary sneakers clothing pack, jordan knit skate fly womens max inspired.");
INSERT into product_description (description) VALUES ("Access vapormax jordan upper ultra retro, court mens equality premium swoosh. Transformation jordan essentials cortez culture swoosh, sport innovation custom strike. Court access retro member brand access offwhite icon collection.");
INSERT into product_description (description) VALUES ("Exclusive futuristic future ignite futuristic collection, swoosh futuristic culture run force zoom importance clothing. Launch swoosh court collection pattern available, trancendant importance shilouette futuristic member hurache. Ethos significant exclusive run fly knit training air.");
INSERT into product_description (description) VALUES ("Upper retro versatile retailers skate special strike stength hurache. Pack innovate significant explore legendary retailers strike future. Jordan versatile clothing max quick, ignite offwhite icon cortez strike trancendant strike innovate access.");        
INSERT into product_description (description) VALUES ("Homage limitless flyknit available importance ultra sneakers, mens pattern stength ultra athlete flight. Advance future knit world culture, inspired unlock fly unlock advance. Shilouette finesse stealth run access stength skate pack.");
INSERT into product_description (description) VALUES ("Fly brand icon, access athlete unlock virgil limitless virgil sport ethos flyknit gear. Attack sneakers skate culture, tech pattern vapormax force access fly launch. Court versatile breaking pack kickoff pattern versatile.");
INSERT into product_description (description) VALUES ("Advance retro shilouette air quick global shilouette available, offwhite upper access knit. Skate innovation hurache air, stealth breaking knit attack womens retro. Court force gear knit force fly cortez brand.");
INSERT into product_description (description) VALUES ("Access limitless jordan knit special collection offwhite. Knit brand strike unlock court collection finesse clothing innovate, force stealth custom stength run. Explore premium custom cortez, gear trancendant retro exclusive ethos classic.");
INSERT into product_description (description) VALUES ("Gear attack inspired shilouette mens special retailers trancendant upper. Ethos access breaking retro strike jordan, equality upper knit equality. Significant significant icon limitless icon mens classic stealth.");
INSERT into product_description (description) VALUES ("Retro hurache ethos pattern, essentials lab innovation virgil access lab gear exclusive clothing pack. Flight essentials legendary exclusive reserved innovation quick culture, retro vapormax kickoff collection. Advance womens pattern exclusive, retailers offwhite access access exclusive max.");
INSERT into product_description (description) VALUES ("Cortez inspired flight virgil gear custom equality. Ignite air flyknit vapormax significant exclusive heritage vapormax, pattern sport innovation retailers available. Sport athlete pattern mens reserved breaking culture.");
INSERT into product_description (description) VALUES ("Mens collection athlete, vapormax flyknit clothing gear global zoom vapormax member fly. Legendary max versatile launch jordan global zoom, heritage court futuristic ignite trancendant. Strike vapormax retailers flyknit knit, classic access reserved world special fly.");
INSERT into product_description (description) VALUES ("Air unlock pack future pattern classic, offwhite quick flight stength classic. Reserved fly style future unlock versatile max womens premium, access global access mens legendary. Collection lab importance launch gear, flight quick world collection innovation attack stealth culture unlock.");
INSERT into product_description (description) VALUES ("Virgil style limitless reserved collection athlete zoom. Tech exclusive inspired snkrs limitless hurache special quick access. Virgil collection custom cortez swoosh ignite, flyknit finesse trancendant attack clothing strike lab retailers.");
INSERT into product_description (description) VALUES ("Cortez finesse explore run force gear exclusive. Classic limitless unlock collection brand fly world 
ethos. World max offwhite brand essentials explore trancendant training breaking skate, finesse ethos retro transformation.");
INSERT into product_description (description) VALUES ("Collection strike gear max access premium athlete flight tech. Collection mens finesse explore mens attack access kickoff, access reserved flyknit premium heritage. Limitless premium breaking available finesse strike, explore reserved pattern custom reserved.");
INSERT into product_description (description) VALUES ("Unlock available transformation kickoff futuristic breaking legendary. Athlete unlock ignite cortez, 
future shilouette finesse importance run quick significant jordan. Ignite virgil transformation kickoff member gear training virgil attack.");
INSERT into product_description (description) VALUES ("Lab quick cortez skate ethos sneakers finesse, sport reserved ignite retro. Explore virgil virgil stealth pattern classic upper kickoff knit. Training stealth max athlete exclusive gear flyknit sport.");
INSERT into product_description (description) VALUES ("Fly pack jordan, flyknit style world global court strike clothing. Lab pack womens shilouette athlete transformation flyknit collection. Training versatile ethos world stength snkrs gear transformation run.");
INSERT into product_description (description) VALUES ("Max global stealth fly training access, court virgil run mens explore. Significant pattern world access essentials future equality, upper unlock versatile upper swoosh. Quick vapormax style sport legendary running collection explore equality custom, innovate style lab world.");
INSERT into product_description (description) VALUES ("Finesse heritage stealth finesse versatile, advance cortez lab run gear special sport sport. Skate heritage launch max style reserved, womens global ignite vapormax. Significant cortez icon, run shilouette shilouette style running access classic stealth unlock athlete future.");
INSERT into product_description (description) VALUES ("Retro gear jordan mens, global heritage collection running launch flight gear. Swoosh inspired tech ethos clothing brand training. Equality access gear, sport athlete running retro versatile ultra homage icon mens.");
INSERT into product_description (description) VALUES ("Knit available available member inspired member, access shilouette clothing jordan world. Culture zoom ethos homage advance gear womens. Offwhite significant unlock innovation, innovation world max future lab sport vapormax.");
INSERT into product_description (description) VALUES ("Custom finesse athlete, swoosh trancendant launch swoosh heritage homage brand collection reserved. Versatile jordan collection unlock retro vapormax, athlete gear classic athlete. Icon trancendant style fly, versatile stength flyknit member significant icon style.");
INSERT into product_description (description) VALUES ("Jordan training significant world world trancendant versatile, jordan swoosh significant culture run 
snkrs heritage. Transformation skate vapormax member significant homage womens versatile. Exclusive womens collection limitless advance shilouette jordan retro shilouette jordan, sport access hurache unlock.");
INSERT into product_description (description) VALUES ("Tech special court training equality flight swoosh access stealth. Gear legendary versatile cortez fly finesse collection flight unlock, classic launch style knit retailers. Vapormax limitless quick pack clothing equality run, virgil trancendant launch brand.");
INSERT into product_description (description) VALUES ("Zoom lab homage collection style heritage icon, inspired member sport jordan ethos knit. Running collection hurache max world court, significant clothing heritage attack limitless exclusive. Stealth strike significant stength, access future pack versatile flyknit air equality run.");
INSERT into product_description (description) VALUES ("Versatile air strike unlock court equality culture equality, heritage ultra importance skate homage. 
Exclusive importance sport exclusive womens world equality, sneakers retro lab explore. Training retailers quick custom running innovation hurache, snkrs air inspired premium run retailers importance.");
INSERT into product_description (description) VALUES ("Special ultra stength exclusive brand, finesse jordan culture hurache retro swoosh attack. Heritage running limitless gear limitless available exclusive flight, access explore quick unlock. Swoosh run training, fly mens kickoff cortez style snkrs athlete sneakers.");
INSERT into product_description (description) VALUES ("Snkrs equality future access ultra ultra, legendary culture jordan retailers retro advance. Upper classic jordan icon available max launch, style collection cortez access equality sport. Exclusive essentials sneakers ignite max essentials innovate unlock, premium futuristic collection reserved.");
INSERT into product_description (description) VALUES ("Training pattern virgil fly sneakers hurache kickoff finesse. Member significant pack icon swoosh force court homage running premium, collection versatile essentials max. Transformation future breaking fly, unlock ultra pack retailers sport max essentials knit flight stealth.");
INSERT into product_description (description) VALUES ("Snkrs classic offwhite inspired, ethos world significant jordan world running gear. World kickoff inspired future launch lab pack member. Unlock ignite collection lab futuristic training flight.");
INSERT into product_description (description) VALUES ("Sneakers inspired icon unlock inspired upper collection. Access retro importance access equality gear heritage collection. Quick upper essentials, advance exclusive zoom sneakers stealth flyknit transformation jordan stength.");
INSERT into product_description (description) VALUES ("Futuristic ultra ultra shilouette, classic heritage trancendant tech access virgil. Innovation fly run skate virgil shilouette jordan court gear, lab launch flight icon. Inspired air premium ultra strike training, snkrs available hurache equality finesse pattern.");
INSERT into product_description (description) VALUES ("Limitless icon world flight innovate, access versatile legendary limitless innovation equality collection inspired gear. Zoom custom strike zoom breaking limitless flyknit offwhite culture. Explore knit significant ignite vapormax upper zoom skate, breaking member run homage.");
INSERT into product_description (description) VALUES ("Shilouette gear unlock lab strike stength run reserved, vapormax court retailers classic. Training heritage versatile pattern running reserved style. Sport ethos max unlock essentials, future mens attack importance importance explore.");
INSERT into product_description (description) VALUES ("Athlete equality breaking advance, heritage heritage retro homage ultra available style. Legendary sneakers transformation future innovation exclusive, run essentials fly special. Limitless skate run world, member hurache flight icon special brand shilouette.");
INSERT into product_description (description) VALUES ("Tech legendary premium equality flyknit equality culture explore. Premium ignite flight vapormax offwhite innovation legendary kickoff. Reserved tech jordan, vapormax ultra snkrs exclusive stealth homage available.");
INSERT into product_description (description) VALUES ("Reserved run world importance offwhite culture stealth explore ultra. Homage launch member advance vapormax hurache mens launch. Retailers special legendary pattern vapormax world culture athlete jordan.");
INSERT into product_description (description) VALUES ("Fly legendary equality culture custom sport cortez ethos collection, womens retailers global court. Tech member special virgil essentials stealth sneakers premium. Premium retailers zoom jordan hurache air global.");
INSERT into product_description (description) VALUES ("Access limitless style tech finesse futuristic athlete pack training. Shilouette advance ignite unlock sport womens strike. Access ignite equality innovate flight unlock lab reserved.");
INSERT into product_description (description) VALUES ("Snkrs transformation brand culture innovation collection access stength trancendant swoosh, world future virgil advance. Max reserved gear exclusive training hurache collection access, limitless knit air quick future skate. Homage available gear launch run 
hurache collection breaking fly.");
INSERT into product_description (description) VALUES ("Inspired futuristic innovate stength strike stength breaking access style. Significant innovate premium launch, fly future importance mens retailers limitless. Snkrs gear collection special clothing mens equality transformation, world finesse style stength 
premium.");
INSERT into product_description (description) VALUES ("Access pattern collection air futuristic max, air run clothing womens. Training court innovation retro premium legendary innovation hurache. Tech inspired max member brand access, force force explore sneakers significant lab limitless.");
INSERT into product_description (description) VALUES ("Essentials world run gear, flyknit inspired finesse force equality force force virgil. Advance run importance ignite upper cortez, vapormax essentials breaking future air offwhite. Futuristic classic access member classic innovation unlock unlock.");       
INSERT into product_description (description) VALUES ("Inspired trancendant upper attack transformation air reserved global, versatile finesse retro virgil 
shilouette. Ignite significant custom heritage snkrs virgil hurache gear, clothing air premium exclusive. Ignite custom run, explore stealth launch culture 
homage athlete access training pattern.");
INSERT into product_description (description) VALUES ("Style advance gear sport, retro kickoff upper max access transformation ignite inspired court. Hurache reserved special significant swoosh upper snkrs, kickoff advance importance innovation. Ultra innovation trancendant gear inspired homage, inspired air vapormax available gear strike running limitless.");
INSERT into product_description (description) VALUES ("Future pack finesse, force stength training clothing heritage retailers fly. Stealth gear sneakers global exclusive womens equality importance. Advance equality available, fly attack vapormax flight innovation pack special access.");
INSERT into product_description (description) VALUES ("Premium culture training heritage tech unlock stength. Available inspired offwhite heritage world ethos virgil. Gear advance classic ignite brand attack upper, strike training collection skate.");
INSERT into product_description (description) VALUES ("Skate run access innovate brand max gear finesse, court swoosh upper world. Available collection custom classic skate equality court, force hurache clothing equality womens. Running run swoosh, retailers air skate icon attack breaking cortez equality equality.");
INSERT into product_description (description) VALUES ("Womens innovation kickoff futuristic gear pattern retailers special, reserved ignite air vapormax finesse pack. Knit retro ultra ultra unlock offwhite swoosh. World cortez innovate womens importance, mens limitless shilouette explore style lab flyknit athlete innovate.");
INSERT into product_description (description) VALUES ("Trancendant innovate kickoff unlock jordan legendary lab culture strike, vapormax reserved advance jordan retailers. Lab classic access zoom, homage global flight gear run court jordan style force. Exclusive transformation global equality zoom knit max stealth.");
INSERT into product_description (description) VALUES ("Available quick force innovation offwhite future tech clothing pack, available versatile attack innovate icon. Snkrs cortez gear, collection jordan mens brand force innovation essentials. Advance style world exclusive, mens member offwhite cortez transformation style premium.");
INSERT into product_description (description) VALUES ("Versatile stength shilouette trancendant collection, brand equality collection retailers innovate training knit. Vapormax clothing athlete kickoff special innovation launch, significant max special force style mens. Knit breaking collection advance zoom, member versatile vapormax pattern snkrs ethos.");
INSERT into product_description (description) VALUES ("Max equality transformation legendary stength air jordan. Heritage transformation legendary, stealth 
collection run gear icon exclusive shilouette. Gear launch access, stength trancendant ethos force limitless swoosh exclusive athlete pattern sport.");     
INSERT into product_description (description) VALUES ("Culture vapormax attack pattern ethos hurache brand flight pattern, importance jordan homage lab pattern. Cortez access womens womens upper versatile pattern, style mens culture trancendant heritage. Special collection cortez limitless essentials importance flight, pattern offwhite sport futuristic retro.");
INSERT into product_description (description) VALUES ("Jordan kickoff athlete flight training gear, force retro pattern significant court trancendant ultra. Future run significant brand athlete, ignite icon sneakers upper legendary jordan. Culture reserved force icon stealth jordan access, futuristic collection snkrs flyknit flight gear clothing.");
INSERT into product_description (description) VALUES ("Virgil strike significant stength jordan training offwhite court, launch jordan lab essentials hurache ultra. Explore womens force fly, unlock sneakers transformation access running special virgil strike knit. Attack court stength sport offwhite kickoff flight, breaking classic advance finesse.");
INSERT into product_description (description) VALUES ("Stealth breaking unlock max mens inspired clothing classic. Collection ultra pattern breaking importance skate fly icon virgil. Heritage hurache run significant style athlete, tech inspired retro strike.");
INSERT into product_description (description) VALUES ("Advance importance attack shilouette, ethos sneakers stength quick special launch. Retro lab premium 
run explore retro clothing swoosh. Classic retro fly collection max, importance finesse significant running offwhite mens kickoff retailers futuristic.");  
INSERT into product_description (description) VALUES ("Inspired access unlock retro training style, gear training exclusive collection ethos. Court sneakers transformation vapormax finesse, brand global ultra explore trancendant womens access air. Quick significant global special swoosh stength icon ignite retro.");
INSERT into product_description (description) VALUES ("Snkrs explore innovate cortez, innovation member sport swoosh run reserved lab gear explore ethos. Pack transformation kickoff knit, lab pack quick flyknit exclusive vapormax gear swoosh culture. Legendary collection tech retailers swoosh pack upper.");    
INSERT into product_description (description) VALUES ("Knit trancendant reserved equality lab fly swoosh. Style culture fly pattern breaking innovation future. Collection court homage max brand sport stength tech.");
INSERT into product_description (description) VALUES ("Attack sneakers breaking reserved mens retailers ignite. Shilouette training sport access, stealth ignite breaking flight explore running access. Explore mens sneakers cortez importance force transformation.");
INSERT into product_description (description) VALUES ("Fly snkrs transformation run ethos clothing court. Style gear retro training, running world ultra style future womens. Skate stealth attack ultra flyknit, access shilouette hurache unlock cortez member vapormax running future.");



